### ISSUE TITLE
Sakarya and LiuChen questions

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [williamgilpin/dysts#10]
Hi, I've been looking at the implementations of the Sakarya and LiuChen systems and I have a couple of questions. It's my understanding that, since the two systems are similar, the implementation is based on the same equations, simply changing the free parameters. Although looking at the equations in "A novel four-wing strange attractor born in bistability" the second equation reads as
```math
\dot{y} = -xz + yz
```
while in the [code](https://github.com/williamgilpin/dysts/blob/master/dysts/flows.py#L825) it's implemented as `ydot = -b * y - p * x + q * x * z`. Should this be `ydot = b * yz - p * y + q * x * z` (also accounting for the LiuChen and adjusting the parameters) or there is something I am overlooking?

Also the third equation 
```math
\dot{z} = -z - mxy + b
```
is implemented as ` zdot = c * z - r * x * y`. is there a reason to not include the `+b`? 

Wouldn't be more straight forward to implement the two systems as separate to increase readability?

Sorry in advance if I missing something obvious, and thanks for this work I've been really enjoying the repo!

**Comment by williamgilpin** [comment]
Hi, I agree that it might make the most sense to have these as separate systems. I can make a note to split these out in a future release. Are there any errors in the implementations, or am I free to go ahead and separate them while keeping the same dynamics? Thanks very much for looking into this!

**Comment by williamgilpin** [comment]
Closing this issue for now
