### ISSUE TITLE
ModuleNotFoundError: No module named 'degas'

### ISSUE THREAD

**Issue by kpark53** [williamgilpin/dysts#13]
Hi Dr.Gilpin,

 Thank you for the amazing work and benchmark. I was wondering what the module named 'degas' is. I can't seem to find it on pypi or conda forge. Could you please advise?

Best,
Keun

**Comment by williamgilpin** [comment]
Thank you very much. This dependency is not necessary---I should remove it. 
Where did you encounter it? It's [just a library I use to make plots](https://github.com/williamgilpin/degas)

**Comment by kpark53** [comment]
oh, that makes sense. I encountered it at demo.ipynb and figure_symbolic_regression_benchmark.ipynb
