### ISSUE TITLE
Request for Detailed Implementation of Machine Learning Algorithms as Described in Figure 2 of the Main Paper

### ISSUE THREAD

**Issue by munozdjp** [williamgilpin/dysts#15]
Dear William

I hope this message finds you well. I am reaching out to express a difficulty I encountered while navigating through the API documentation linked in your repository. Upon review, I was able to find detailed documentation on generating trajectories from dynamical systems. However, I was unable to locate the specifics regarding the implementation of the machine learning algorithms, particularly those pertaining to RNN and LSTM.

The main paper's Figure 2 references the implementation of various machine learning methods, and I am particularly interested in the transformer architecture discussed. Your paper notes that "Transformers can capture long-term dependencies and complex patterns in time series data by using positional encoding and multihead attention, leading to their widespread use for diverse problems such as machine translation, text summarization, and question answering [63]".

Could you kindly provide or point me to the detailed implementation of these machine learning algorithms, especially the transformer model? The code snippets, examples, or documentation that illustrate the transformer's application specifically on you dynamical systems would be incredibly beneficial.

I appreciate the work you've put into this project and look forward to exploring the machine learning aspects further.

Thank you for your time and assistance.

**Comment by williamgilpin** [comment]
Hi, it is in the benchmarks directory:
https://github.com/williamgilpin/dysts/tree/master/benchmarks

I used the Transformer implementation found in the darts python library
