### ISSUE TITLE
Integration timestep inconsistency between returned values and metadata

### ISSUE THREAD

**Issue by dtretiak3** [williamgilpin/dysts#18]
There appears to be some inconsistency between the timestep listed in the metadata for a dyst.flow equation vs the one actually used. See below for an illustration: 

```
import dysts.flows
eq = dysts.flows.Lorenz()
t, U = eq.make_trajectory(1000, return_times = True)
print('Returned dt: ', (np.diff(t)[0]))
print('Metadata dt: ', eq.dt)
```

Output:
```
Returned dt:  0.015023023023023023
Metadata dt:  0.0001801
```

**Comment by williamgilpin** [comment]
Hi, the metadata dt is used internally by the integrator to ensure sufficient precision. The mesh dt depends on the number of timepoints you ask it to generate (as well as the default granularity). You can disable this behavior by setting `resample=False` when you call `make_trajectory`
