### ISSUE TITLE
Error when using the library

### ISSUE THREAD

**Issue by manastahir** [williamgilpin/dysts#31]
Installed the library from PyPI and from github directly. 
Getting the same error.

![image](https://github.com/user-attachments/assets/22a97f21-99f2-4671-86db-32c27cdacad6)

**Comment by williamgilpin** [comment]
@jbial any idea? it looks like this should have worked because of [__init__.py](https://github.com/williamgilpin/dysts/blob/master/dysts/utils/__init__.py)

**Comment by williamgilpin** [comment]
Actually maybe we need to change [the other init](https://github.com/williamgilpin/dysts/blob/master/dysts/__init__.py) that's in the same directory as base? These python internal links always confuse me

**Comment by jbial** [comment]
@williamgilpin We prob have to rebuild the package with the recent structure changes

**Comment by williamgilpin** [comment]
@manastahir I've updated the build and pushed a new version to PyPI, see if either one works for you

**Comment by williamgilpin** [comment]
@manastahir it turns out that this is a trickier issue than we thought. we are working on resolving it

**Comment by jbial** [comment]
@manastahir should be resolved now, try importing again!

**Comment by mkanwal** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/2c661c38-6923-4494-8d96-22827b3f9ef0">

**Comment by williamgilpin** [comment]
hey @mkanwal ! 
Thanks for letting us know @jbial and I will work on getting this fixed today

**Comment by williamgilpin** [comment]
@mkanwal it turned out that I uploaded 0.95 to testpypi instead of pypi 🙃
see if 0.95 (now on PyPI) fixes it

**Comment by mkanwal** [comment]
Working! 😄

**Comment by williamgilpin** [comment]
we're so back. thanks for letting us know
