### ISSUE TITLE
Significant Change in Lorenz Model Behavior After Recent Update

### ISSUE THREAD

**Issue by IoannisK97** [williamgilpin/dysts#34]
I have been using the dysts library for the past month for my dissertation that includes chaotic system forecasting. I use the library to generate data and so far I have been using the Lorenz system. After the most recent update I noticed that the data generated from the Lorenz model using make_trajectory have been different after 10000 steps. 
![image](https://github.com/user-attachments/assets/8a692672-fc88-4e6f-88b9-181671d981c4). 
This is the code I have been using the default values both for parameters and initial conditions. 
Here are some screenshots of the different data
Most recent: 
![image](https://github.com/user-attachments/assets/cbcb5e98-748e-41b0-9a26-0768ef5c1a6f)
 and what I generated 24 hours ago
 
![image](https://github.com/user-attachments/assets/77ffd71f-d56f-42fe-b6e1-6d5646853e2a)
I always use this line to install dysts on my Colab Notebooks
`!pip install `git+https://github.com/williamgilpin/dysts``

**Comment by williamgilpin** [comment]
Hi, we've been making a lot of improvements,  and it's possible that the integrator changed slightly. Do I correctly understand that the first timepoints are right, but it diverges over time? It could be that our default IC precision changed in a recent update.

The easiest fix would be to import from PyPI in your Colab notebook, and set a fixed version number like 0.92

**Comment by IoannisK97** [comment]
Hello, I actually get the same error as in this issue https://github.com/williamgilpin/dysts/issues/31 . I guess when you work with chaotic systems data then you have to be prepared to get some chaos. In any case I believe your collection of attractors can be useful even without generating data. Thank you.

**Comment by williamgilpin** [comment]
Hi, what version is failing the install? You can also try rolling back to a specific GitHub commit. For example,

`
pip install git+https://github.com/williamgilpin/dysts.git@1f4c374ae6208acf9ce9d19fe37ef9abf1b3e396
`

**Comment by IoannisK97** [comment]
I tried versions 0.92, 0.93 and 0.94 using PyPi. Any way right now I am generating data by myself, altough I have to say the resources and citations in data/chaotic_attractors.json were much useful in the process.

**Comment by williamgilpin** [comment]
Ah I see the issue, I think 0.95 is where we finally fixed #31 , but i think we made changes to the integrator in that update too.

do you know which version you had that was stable? we can try to dig up the commit hash to freeze it

**Comment by IoannisK97** [comment]
I could not find the exact version. The commit that made me open the issue was on October 24. I see there are three commits on that day. I am in UK time zone and at about 10:00 am here I got different data than the day before. I hope this helps.

**Comment by jbial** [comment]
@IoannisK97 Try it now, I realized there was a bug with the way the period was getting instantiated with some recent structural changes in base.py

**Comment by williamgilpin** [comment]
@IoannisK97 You might also try this version

`
pip install dysts==0.81
`

**Comment by jbial** [comment]
@IoannisK97 Another factor (and prob a better explanation) for the discrepancy you are observing is that in the newer versions of dysts, we set the `rtol` and `atol` parameters by default to 1e-12, whereas the scipy default tolerances were used in the previous version. You can reproduce the old behavior: `model.make_trajectory(..., rtol=None, atol=None)`

**Comment by jbial** [comment]
@IoannisK97 no worries! I'll go ahead and close this issue.
