### ISSUE TITLE
Accessing Dynamical Embedding Class Information for each Attractor

### ISSUE THREAD

**Issue by mgaimann** [williamgilpin/dysts#35]
Is there somewhere a list that allocates each attractor presented in this repo to one embedding class (lobes, rotations, twists, spikes, etc.) shown in [this figure](https://github.com/williamgilpin/dysts/blob/master/dysts/data/fig_github.png) and Fig. 1A in [this paper](https://arxiv.org/pdf/2110.05266)?

I would like to select one attractor from each class to perform benchmarking, but I could not find this allocation, unfortunately.

Ideally, this information would be available in [`chaotic_attractors.json`](https://github.com/williamgilpin/dysts/blob/master/dysts/data/chaotic_attractors.json) or a separate file in a machine-readable format.

Thank you for your help!

**Comment by jbial** [comment]
unfortunately, I dont think we'll be providing this information any time soon as these qualitative features would require manually labeling every system (as far I can tell)

**Comment by mgaimann** [comment]
Hi @jbial, thank you for looking into this! 

Would it be possible to provide just a few examples for each dynamical class? 
Maybe for the most prominent attractors (e.g. Rotations -> Roessler, Ripples -> Lorenz96, Jumps -> ?) ? 

This would help me and others to use your attractors from different dynamical classes for benchmarking.

**Comment by jbial** [comment]
@mgaimann I'm just not sure if there is a way to unambiguously classify systems with these qualitative descriptors you mention. For example, what exactly is the "rotations" label for rossler or "ripples" for Lorenz96? 

For now, I'll be closing this issue due to the labeling ambiguity. However, we'd be happy to look over a PR if you have some idea!

**Comment by mgaimann** [comment]
> For example, what exactly is the "rotations" label for rossler or "ripples" for Lorenz96?

@jbial The labels refer to the descriptors introduced in [this publication](https://arxiv.org/pdf/2110.05266) associated with this repo, to the embeddings in Figure 1A (lobes, rotations, twists, spikes, ripples, drifts, jumps, shifts).

In the publication, the embeddings do not seem very ambiguous, because each attractor seems to have been allocated to one of these dynamical classes. 

I really appreciate the time and effort invested in maintaining this repo, and I understand the limited time available. Should there be the possibility to list a few examples per embedding class here in the future I would be very grateful.
