### ISSUE TITLE
Suggestion for chaotic system

### ISSUE THREAD

**Issue by akaptano** [williamgilpin/dysts#5]
Wow, awesome job with this! I'm going to add an example of using these datasets with some of the PySINDy repository's new functionality -- will update you on progress.

Also, you may be interested in adding the chaotic "atmospheric oscillator" from Tuwankotta, J. M. (2003). Widely separated frequencies in coupled oscillators with energy-preserving quadratic nonlinearity. Physica D: Nonlinear Phenomena, 182(1-2), 125-149. Our group also uses a simple version of this system in Kaptanoglu, A. A., Callaham, J. L., Aravkin, A., Hansen, C. J., & Brunton, S. L. (2021). Promoting global stability in data-driven models of quadratic nonlinear dynamics. Physical Review Fluids, 6(9), 094401.

**Comment by williamgilpin** [comment]
Hey @akaptano , my apologies for the delay on this---the issue that I am running into is that to add new systems, I need to make sure that all of the different features are included (Lyapunov exponents, best timescale, precomputed trajectories). I also need to freeze a version for the benchmarks reported in the paper. 

I'm currently working on automating most of this

**Comment by williamgilpin** [comment]
Hey @akaptano this is now included in the GitHub version:
```
pip install git+git://github.com/williamgilpin/dysts
```

I included estimates of Lyapunov exponents and other metadata that the other systems have. It should work the same as other systems

```
from dysts.flows import AtmosphericRegime

eq = AtmosphericRegime()
sol = eq.make_trajectory(1000)
plt.plot(sol[:, 0], sol[:, 1])
```

Thanks for sharing the info and snippet---very interesting system with the two timescales

**Comment by akaptano** [comment]
Agreed, thanks for implementing.
